(()=>{"use strict";const $=id=>document.getElementById(id),homeScreen=$("homeScreen"),levelsScreen=$("levelsScreen"),gameScreen=$("gameScreen"),startBtn=$("startBtn"),homeLevelsBtn=$("homeLevelsBtn"),backHomeBtn=$("backHomeBtn"),gameBackBtn=$("gameBackBtn"),soundBtn=$("soundBtn"),settingsBtn=$("settingsBtn"),settingsPanel=$("settingsPanel"),resetProgressBtn=$("resetProgressBtn"),closeSettingsBtn=$("closeSettingsBtn"),resultPanel=$("resultPanel"),resultIcon=$("resultIcon"),resultTitle=$("resultTitle"),resultText=$("resultText"),resultScore=$("resultScore"),resultPrimaryBtn=$("resultPrimaryBtn"),resultSecondaryBtn=$("resultSecondaryBtn"),levelsGrid=$("levelsGrid"),canvas=$("gameCanvas"),ctx=canvas.getContext("2d"),levelNumber=$("levelNumber"),scoreText=$("scoreText"),bestText=$("bestText"),pressureDots=$("pressureDots"),currentBubble=$("currentBubble"),nextBubble=$("nextBubble"),message=$("message"),W=480,H=760;canvas.width=W;canvas.height=H;const COLS=11,RADIUS=20,DIAMETER=40,ROW_HEIGHT=35,TOP_Y=48,SHOOTER_X=W/2,SHOOTER_Y=690,DANGER_Y=590,MAX_LEVEL=50,MISS_LIMIT=3,SAVE_KEY="bulbuleKaKhelSave",COLORS=[{name:"red",main:"#dc5267",light:"#ffb6bd",dark:"#86283d",pattern:"lotus"},{name:"yellow",main:"#ddc34e",light:"#fff2a7",dark:"#94751c",pattern:"sun"},{name:"green",main:"#59aa76",light:"#c2efd0",dark:"#275e43",pattern:"leaf"},{name:"blue",main:"#5791d0",light:"#c5e1ff",dark:"#28588f",pattern:"wave"},{name:"purple",main:"#9569c3",light:"#e0c8ff",dark:"#553080",pattern:"peacock"},{name:"pink",main:"#d57698",light:"#ffd4e1",dark:"#873d5b",pattern:"flower"}],SPECIAL_ICONS={laser:"⚡",bomb:"💣",rainbow:"🌈",sun:"☀"},defaultSave={currentLevel:1,unlocked:1,completed:[],bestScores:{},best:0,sound:!0};let save=loadSave(),grid=[],currentColor=0,nextColor=1,currentSpecial=null,nextSpecial=null,score=0,missedShots=0,busy=!1,paused=!1,gameEnded=!1,levelWon=!1,movingBubble=null,fallingBubbles=[],particles=[],popEffects=[],rings=[],impacts=[],specialBursts=[],bubbleWobbles=[],ceilingAnimation=null,launcherRecoil=0,launcherBounce=0,shake=0,aimX=SHOOTER_X,aimY=300,pointerHolding=!1,activePointerId=null,audioContext=null,shotsToSpecial=8+Math.floor(2*Math.random()),lastTime=0,gameSession=0,actionSerial=0,currentActionId=0,messageTimer=null,messageAnimation=null;

function nextActionId(){return currentActionId=++actionSerial}
function guardedTimeout(callback,delay,session=gameSession,actionId=null){return setTimeout(()=>{if(session!==gameSession)return;if(null!==actionId&&actionId!==currentActionId)return;callback()},delay)}
function ensureMessageStyles(){if(!message||document.getElementById("bkkMessageStyles"))return;const style=document.createElement("style");style.id="bkkMessageStyles";style.textContent=`#message.bkk-center-message{position:fixed!important;left:50%!important;top:50%!important;transform:translate(-50%,-50%) scale(.94);min-width:150px;max-width:min(82vw,360px);padding:10px 18px;border-radius:16px;background:rgba(10,28,61,.86);border:1px solid rgba(255,238,187,.34);box-shadow:0 10px 28px rgba(0,0,0,.22),inset 0 1px 0 rgba(255,255,255,.13);color:#fff8df;font-size:clamp(15px,4.2vw,19px);font-weight:700;line-height:1.28;text-align:center;letter-spacing:.1px;white-space:normal;pointer-events:none!important;opacity:0;z-index:99999!important;backdrop-filter:blur(7px);-webkit-backdrop-filter:blur(7px);transition:none!important}`;document.head.appendChild(style);message.classList.add("bkk-center-message")}
function showMessage(text,duration=1450){if(!message)return;ensureMessageStyles();message.textContent=text;message.classList.add("bkk-center-message");messageTimer&&(clearTimeout(messageTimer),messageTimer=null);if(messageAnimation)try{messageAnimation.cancel()}catch{}messageAnimation=null;message.style.opacity="0";message.style.transform="translate(-50%,-50%) scale(.94)";messageAnimation=message.animate([{opacity:0,transform:"translate(-50%,-50%) scale(.94)"},{opacity:1,transform:"translate(-50%,-50%) scale(1)",offset:.16},{opacity:1,transform:"translate(-50%,-50%) scale(1)",offset:.78},{opacity:0,transform:"translate(-50%,-50%) scale(.98)"}],{duration,easing:"ease-in-out",fill:"forwards"});messageTimer=setTimeout(()=>{message.style.opacity="0";message.style.transform="translate(-50%,-50%) scale(.98)";messageTimer=null},duration)}
ensureMessageStyles();

function loadSave(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return{...defaultSave,completed:[],bestScores:{}};const data=JSON.parse(raw);return{...defaultSave,...data,currentLevel:Number(data.currentLevel||1),unlocked:Math.max(1,Number(data.unlocked||1)),completed:Array.isArray(data.completed)?data.completed:[],bestScores:data.bestScores||{},best:Number(data.best||0),sound:data.sound!==!1}}catch{return{...defaultSave,completed:[],bestScores:{}}}}
function saveGame(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save))}catch{}}

function levelConfig(){const level=save.currentLevel;return{rows:level>=41?10:level>=31?9:level>=21?8:level>=11?7:6,colors:level>=31?6:level>=17?5:level>=7?4:3}}
function randomColor(){return Math.floor(Math.random()*levelConfig().colors)}
function createSpecialForShot(){if(save.currentLevel<4)return null;if(shotsToSpecial>0)return null;shotsToSpecial=8+Math.floor(2*Math.random());const types=["laser","bomb","rainbow","sun"];return types[Math.floor(Math.random()*types.length)]}
function makeBubble(){return{color:randomColor(),special:null,squish:0,wobble:0,phase:2*Math.PI*Math.random()}}
function createLevel(){gameSession++;nextActionId();messageTimer&&(clearTimeout(messageTimer),messageTimer=null);messageAnimation&&(messageAnimation.cancel(),messageAnimation=null);const config=levelConfig();grid=[];score=0;missedShots=0;busy=!1;paused=!1;gameEnded=!1;levelWon=!1;movingBubble=null;fallingBubbles=[];particles=[];popEffects=[];rings=[];impacts=[];specialBursts=[];bubbleWobbles=[];ceilingAnimation=null;launcherRecoil=0;launcherBounce=0;shake=0;shotsToSpecial=8+Math.floor(2*Math.random());for(let r=0;r<config.rows;r++){const row=[];for(let q=0;q<COLS;q++){let bubble=makeBubble();if(r>1&&save.currentLevel>=8&&Math.random()<.05)bubble=null;row.push(bubble)}grid.push(row)}for(let q=0;q<COLS;q++)grid[0][q]||(grid[0][q]=makeBubble());removeStartingMatches();currentColor=randomColor();nextColor=randomColor();currentSpecial=null;nextSpecial=null;aimX=SHOOTER_X;aimY=300;updateUI();showMessage("निशाना लगाइए")}
function removeStartingMatches(){for(let pass=0;pass<8;pass++){let changed=!1;for(let r=0;r<grid.length;r++)for(let q=0;q<COLS;q++){const bubble=grid[r][q];if(!bubble||bubble.special)continue;const group=findCluster(q,r,bubble.color);if(group.length>=3){const target=group[Math.floor(Math.random()*group.length)];grid[target[1]][target[0]]=makeBubble();changed=!0}}if(!changed)break}}

function getX(q,r){return RADIUS+q*DIAMETER+(r%2?RADIUS:0)}
function getY(r){return TOP_Y+r*ROW_HEIGHT}
function position(q,r){return{x:getX(q,r),y:getY(r)}}
function inside(q,r){return q>=0&&q<COLS&&r>=0&&r<grid.length}
function neighbors(q,r){const odd=r%2===1,dirs=odd?[[-1,0],[1,0],[0,-1],[1,-1],[0,1],[1,1]]:[[-1,0],[1,0],[-1,-1],[0,-1],[-1,1],[0,1]];return dirs.map(([dq,dr])=>[q+dq,r+dr]).filter(([nq,nr])=>inside(nq,nr))}
function findCluster(startQ,startR,color){const start=grid[startR]?.[startQ];if(!start||start.special||start.color!==color)return[];const stack=[[startQ,startR]],seen=new Set,result=[];while(stack.length){const[q,r]=stack.pop(),key=q+","+r;if(seen.has(key))continue;seen.add(key);const bubble=grid[r]?.[q];if(!bubble||bubble.special||bubble.color!==color)continue;result.push([q,r]);for(const neighbour of neighbors(q,r))stack.push(neighbour)}return result}
function connectedToCeiling(){const result=new Set,stack=[];for(let q=0;q<COLS;q++)if(grid[0]?.[q]){result.add(q+",0");stack.push([q,0])}while(stack.length){const[q,r]=stack.pop();for(const[nq,nr]of neighbors(q,r)){if(!grid[nr]?.[nq])continue;const key=nq+","+nr;if(!result.has(key)){result.add(key);stack.push([nq,nr])}}}return result}
function findBestAttachment(x,y){let best=null,bestDistance=Infinity;for(let r=0;r<grid.length;r++)for(let q=0;q<COLS;q++){if(grid[r][q])continue;const hasNeighbor=neighbors(q,r).some(([nq,nr])=>Boolean(grid[nr]?.[nq]));if(!hasNeighbor&&r!==0)continue;const p=position(q,r),distance=Math.hypot(p.x-x,p.y-y);if(distance<bestDistance){bestDistance=distance;best=[q,r]}}if(!best){grid.push(new Array(COLS).fill(null));best=[Math.floor(COLS/2),grid.length-1]}return best}

function shoot(){if(busy||paused||gameEnded||levelWon||ceilingAnimation)return;initAudio();busy=!0;launcherRecoil=1;launcherBounce=1;let dx=aimX-SHOOTER_X,dy=aimY-SHOOTER_Y;if(dy>-55)dy=-55;const distance=Math.hypot(dx,dy)||1,speed=820,actionId=nextActionId();movingBubble={x:SHOOTER_X,y:SHOOTER_Y-4,vx:dx/distance*speed,vy:dy/distance*speed,color:currentColor,special:currentSpecial,scale:.82,squash:0,rotation:0,trail:[],actionId};shotsToSpecial--;currentColor=nextColor;currentSpecial=nextSpecial;nextColor=randomColor();nextSpecial=createSpecialForShot();updateUI();playSound(330,.06,"sine",.025)}
function finishShot(){if(!movingBubble)return;const shot=movingBubble;if(shot.actionId!==currentActionId)return;const[q,r]=findBestAttachment(shot.x,shot.y),bubble={color:shot.color,special:shot.special||null,squish:1,wobble:1,phase:2*Math.PI*Math.random()};grid[r][q]=bubble;const p=position(q,r);movingBubble=null;impacts.push({x:p.x,y:p.y,life:0,max:.26});createParticles(p.x,p.y,bubble.color,7);rings.push({x:p.x,y:p.y,color:bubble.color,life:0,max:.28});if(bubble.special){activateSpecial(q,r,bubble.special,shot.actionId);return}const group=findCluster(q,r,bubble.color);if(group.length>=3)handleMatch(group,shot.actionId);else{softWobble(q,r);missedShots++;if(missedShots>=MISS_LIMIT){missedShots=0;descendCeiling(shot.actionId)}else{showMessage(missedShots===1?"अच्छा निशाना!":"बस एक मौका और…");busy=!1}}updateUI();isBoardEmpty()&&completeLevel()}
function softWobble(q,r){for(const[nq,nr]of neighbors(q,r)){const bubble=grid[nr]?.[nq];if(!bubble)continue;bubble.wobble=1;bubble.squish=.65;bubbleWobbles.push({q:nq,r:nr,life:0,max:.34})}}

function handleMatch(group,actionId){if(actionId!==currentActionId)return;missedShots=0;const count=group.length;score+=count*20;if(count>=5)score+=10*count;for(const[q,r]of group){const bubble=grid[r][q];if(!bubble)continue;bubble.squish=1;bubble.wobble=1;const p=position(q,r);popEffects.push({x:p.x,y:p.y,color:bubble.color,special:null,life:0,max:.42+.08*Math.random(),delay:.06*Math.random(),phase:2*Math.PI*Math.random()});createParticles(p.x,p.y,bubble.color,14);grid[r][q]=null}count>=7?showMessage("गजब कऽ देलियै! ✨"):count>=5?showMessage("अहाँ कमाल कऽ देलियै!"):showMessage("बहुत नीक! 😄");shake=Math.min(8,2+.35*count);playSound(450+30*count,.15,"sine",.045);const session=gameSession;guardedTimeout(()=>{const dropped=dropDetached();score+=45*dropped;updateUI();saveGame();isBoardEmpty()?completeLevel():busy=!1},220,session,actionId)}

function dropDetached(){const connected=connectedToCeiling();let count=0;for(let r=0;r<grid.length;r++)for(let q=0;q<COLS;q++){const bubble=grid[r][q];if(!bubble||connected.has(q+","+r))continue;const p=position(q,r);fallingBubbles.push({x:p.x,y:p.y,color:bubble.color,special:bubble.special,vx:(Math.random()-.5)*85,vy:-70-60*Math.random(),gravity:420,rotation:2*Math.PI*Math.random(),spin:(Math.random()-.5)*4,scale:.98,bounceScale:1,bounceCount:0,grounded:!1,floorY:H-20+65*Math.random(),life:0});grid[r][q]=null;count++}if(count){showMessage(count>=8?"गजब कऽ देलियै! 💫":"अहाँ कमाल कऽ देलियै!");playSound(180,.18,"triangle",.035)}return count}

function activateSpecial(q,r,type,actionId){if(actionId!==currentActionId)return;const p=position(q,r);grid[r][q]=null;specialBursts.push({x:p.x,y:p.y,type,life:0,max:type==="bomb"?.78:.66});missedShots=0;shake=type==="bomb"?12:7;type==="laser"?activateLaser(q,r,actionId):type==="bomb"?activateBomb(q,r,actionId):activateColorSpecial(type==="sun",actionId)}
function clearBubbleAt(q,r){const bubble=grid[r]?.[q];if(!bubble)return;const p=position(q,r);grid[r][q]=null;popEffects.push({x:p.x,y:p.y,color:bubble.color,special:bubble.special,life:0,max:.45,delay:.05*Math.random(),phase:2*Math.PI*Math.random()});createParticles(p.x,p.y,bubble.color,12)}
function activateLaser(q,r,actionId){if(actionId!==currentActionId)return;showMessage("⚡ लेज़र चला!");for(let col=0;col<COLS;col++)grid[r]?.[col]&&clearBubbleAt(col,r);for(let row=0;row<grid.length;row++)grid[row]?.[q]&&clearBubbleAt(q,row);playSound(720,.23,"sawtooth",.04);guardedTimeout(()=>specialFinish(actionId),280,gameSession,actionId)}
function activateBomb(q,r,actionId){if(actionId!==currentActionId)return;showMessage("💥 बम का धमाका!");const center=position(q,r);for(let row=0;row<grid.length;row++)for(let col=0;col<COLS;col++){if(!grid[row][col])continue;const p=position(col,row);Math.hypot(p.x-center.x,p.y-center.y)<=100&&clearBubbleAt(col,row)}playSound(110,.3,"sawtooth",.05);guardedTimeout(()=>specialFinish(actionId),300,gameSession,actionId)}
function mostCommonColor(){const counts={};for(const row of grid)for(const bubble of row)if(bubble&&!bubble.special)counts[bubble.color]=(counts[bubble.color]||0)+1;let best=0,amount=-1;for(const key in counts)if(counts[key]>amount){amount=counts[key];best=Number(key)}return best}
function activateColorSpecial(isSun,actionId){if(actionId!==currentActionId)return;showMessage(isSun?"☀️ सुनहरी चमक!":"🌈 रंगों का जादू!");const color=mostCommonColor();for(let r=0;r<grid.length;r++)for(let q=0;q<COLS;q++){const bubble=grid[r][q];bubble&&!bubble.special&&bubble.color===color&&clearBubbleAt(q,r)}playSound(isSun?620:560,.2,"sine",.04);guardedTimeout(()=>specialFinish(actionId),300,gameSession,actionId)}
function specialFinish(actionId){if(actionId!==currentActionId)return;const dropped=dropDetached();score+=45*dropped;updateUI();saveGame();isBoardEmpty()?completeLevel():busy=!1}

function descendCeiling(actionId){if(actionId!==currentActionId||ceilingAnimation||gameEnded||levelWon)return;busy=!0;const row=new Array(COLS).fill(null);for(let q=0;q<COLS;q++)Math.random()<.86&&(row[q]=makeBubble());row.every(b=>!b)&&(row[Math.floor(COLS/2)]=makeBubble());grid.unshift(row);ceilingAnimation={progress:0,duration:.62};shake=5;showMessage("⚠️ छत एक पंक्ति नीचे आ गई!");playSound(120,.18,"sawtooth",.025)}
function checkDanger(){for(let r=0;r<grid.length;r++)if(grid[r].some(Boolean)&&getY(r)+RADIUS>=DANGER_Y)return!0;return!1}
function isBoardEmpty(){return grid.every(row=>row.every(bubble=>!bubble))}
function completeLevel(){if(levelWon)return;levelWon=!0;busy=!0;const level=save.currentLevel;save.completed.includes(level)||save.completed.push(level);save.unlocked=Math.max(save.unlocked,Math.min(MAX_LEVEL,level+1));save.bestScores[level]=Math.max(save.bestScores[level]||0,score);save.best=Math.max(save.best,score);saveGame();showMessage("बहुत बढ़िया! स्तर पूरा भऽ गेल।");playSound(720,.25,"sine",.055);for(let i=0;i<26;i++)createCelebrationParticle();guardedTimeout(()=>showResult(!0),700,gameSession,currentActionId)}
function endGame(){if(gameEnded)return;gameEnded=!0;busy=!0;showMessage("छत बहुत नीचे आ गई");playSound(100,.3,"sawtooth",.04);guardedTimeout(()=>showResult(!1),600,gameSession,currentActionId)}

function createParticles(x,y,color,count=10){for(let i=0;i<count;i++){const angle=2*Math.PI*Math.random(),speed=55+175*Math.random();particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed-55,color,size:1.5+3*Math.random(),life:0,max:.35+.4*Math.random()})}}
function createCelebrationParticle(){particles.push({x:W*Math.random(),y:20+140*Math.random(),vx:(Math.random()-.5)*160,vy:80+120*Math.random(),color:Math.floor(COLORS.length*Math.random()),size:2+3*Math.random(),life:0,max:.8+.5*Math.random()})}

function update(dt){launcherRecoil=Math.max(0,launcherRecoil-5*dt);launcherBounce=Math.max(0,launcherBounce-4*dt);shake=Math.max(0,shake-16*dt);if(ceilingAnimation){ceilingAnimation.progress+=dt/ceilingAnimation.duration;if(ceilingAnimation.progress>=1){ceilingAnimation.progress=1;ceilingAnimation=null;if(checkDanger()){endGame();return}busy=!1;showMessage("अब निशाना लगाइए 🎯");updateUI()}}for(const row of grid)for(const bubble of row){if(!bubble)continue;if(bubble.squish>0)bubble.squish=Math.max(0,bubble.squish-5*dt);if(bubble.wobble>0)bubble.wobble=Math.max(0,bubble.wobble-3.7*dt);bubble.phase+=2*dt}

if(movingBubble){const b=movingBubble;if(b.actionId===currentActionId){b.trail.push({x:b.x,y:b.y,life:0});if(b.trail.length>12)b.trail.shift();for(const trail of b.trail)trail.life+=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.rotation+=(b.vx/5000)*dt;if(b.x<=RADIUS){b.x=RADIUS;b.vx=Math.abs(b.vx);b.squash=.8}if(b.x>=W-RADIUS){b.x=W-RADIUS;b.vx=-Math.abs(b.vx);b.squash=.8}let hit=!1;for(let r=0;r<grid.length&&!hit;r++)for(let q=0;q<COLS;q++){const cell=grid[r][q];if(!cell)continue;const p=position(q,r);if(Math.hypot(p.x-b.x,p.y-b.y)<=DIAMETER-3){hit=!0;cell.squish=1;cell.wobble=1;impacts.push({x:(p.x+b.x)/2,y:(p.y+b.y)/2,life:0,max:.2});break}}if(b.y<=TOP_Y+RADIUS){b.y=TOP_Y+RADIUS;hit=!0}hit&&finishShot() }else movingBubble=null}

for(let i=fallingBubbles.length-1;i>=0;i--){const b=fallingBubbles[i];b.life+=dt;if(!b.grounded){b.vy+=b.gravity*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;b.rotation+=b.spin*dt;if(b.x<=RADIUS){b.x=RADIUS;b.vx=Math.abs(b.vx)*.8}if(b.x>=W-RADIUS){b.x=W-RADIUS;b.vx=-Math.abs(b.vx)*.8}const floor=Math.min(H-24,b.floorY);if(b.y>=floor){b.y=floor;if(Math.abs(b.vy)>115&&b.bounceCount<2){b.vy=-Math.abs(b.vy)*(b.bounceCount===0?.46:.30);b.vx*=.88;b.bounceCount++;b.bounceScale=1.16;createParticles(b.x,b.y,b.color,3)}else b.grounded=!0}}else b.y+=75*dt;b.bounceScale+=(1-b.bounceScale)*Math.min(1,10*dt);if(b.y>H+110)fallingBubbles.splice(i,1)}

for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life+=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=280*dt;if(p.life>=p.max)particles.splice(i,1)}
for(let i=popEffects.length-1;i>=0;i--){const p=popEffects[i];p.life+=dt;if(p.life>=p.max+p.delay)popEffects.splice(i,1)}
for(let i=rings.length-1;i>=0;i--){rings[i].life+=dt;if(rings[i].life>=rings[i].max)rings.splice(i,1)}
for(let i=impacts.length-1;i>=0;i--){impacts[i].life+=dt;if(impacts[i].life>=impacts[i].max)impacts.splice(i,1)}
for(let i=specialBursts.length-1;i>=0;i--){specialBursts[i].life+=dt;if(specialBursts[i].life>=specialBursts[i].max)specialBursts.splice(i,1)}}

function draw(){ctx.clearRect(0,0,W,H);ctx.save();if(shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawBackground();drawTopLine();drawBubbleGrid();drawFallingBubbles();drawAimGuide();drawLauncher();drawMovingBubble();drawPopEffects();drawRings();drawImpacts();drawParticles();drawSpecialBursts();ctx.restore()}

function drawBackground(){const gradient=ctx.createLinearGradient(0,0,0,H);gradient.addColorStop(0,"#203d70");gradient.addColorStop(.58,"#18345f");gradient.addColorStop(1,"#112a50");ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H);ctx.save();ctx.globalAlpha=.045;ctx.strokeStyle="#efd987";for(let x=25;x<W;x+=70)for(let y=80;y<H;y+=100){ctx.beginPath();ctx.arc(x,y,18,0,2*Math.PI);ctx.stroke();ctx.beginPath();ctx.moveTo(x-14,y);ctx.lineTo(x+14,y);ctx.moveTo(x,y-14);ctx.lineTo(x,y+14);ctx.stroke()}ctx.restore();ctx.save();ctx.globalAlpha=.055;ctx.font="42px serif";ctx.fillText("✦",20,210);ctx.fillText("●",410,420);ctx.fillText("✦",30,590);ctx.fillText("●",410,650);ctx.restore();ctx.save();ctx.globalAlpha=.24;ctx.strokeStyle="#d8bd6f";ctx.setLineDash([5,8]);ctx.beginPath();ctx.moveTo(18,DANGER_Y);ctx.lineTo(W-18,DANGER_Y);ctx.stroke();ctx.restore()}
function drawTopLine(){ctx.save();ctx.globalAlpha=.25;ctx.strokeStyle="#d9bd70";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(12,28);ctx.lineTo(W-12,28);ctx.stroke();ctx.restore()}

function drawBubbleGrid(){for(let r=0;r<grid.length;r++)for(let q=0;q<COLS;q++){const bubble=grid[r][q];if(!bubble)continue;const p=position(q,r);let y=p.y;if(ceilingAnimation){const t=Math.min(1,ceilingAnimation.progress),e=1-Math.pow(1-t,3);y=p.y-ROW_HEIGHT*(1-e)}let sx=1,sy=1,ox=0;if(bubble.wobble>0){const w=Math.sin(4*bubble.phase)*bubble.wobble;sx+=.035*w;sy-=.025*w;ox=1.5*Math.sin(5*bubble.phase)*bubble.wobble}if(bubble.squish>0){sx+=.13*bubble.squish;sy-=.10*bubble.squish}ctx.save();ctx.translate(p.x+ox,y);ctx.scale(sx,sy);bubble.special?drawSpecial(0,0,bubble.special,1,1):drawBubble(0,0,bubble.color,1,1);ctx.restore()}}
function drawBubble(x,y,color,scale=1,alpha=1,rotation=0,sx=1,sy=1){const c=COLORS[color]||COLORS[0];ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.rotate(rotation);ctx.scale(scale*sx,scale*sy);const gradient=ctx.createRadialGradient(-7,-8,2,0,0,RADIUS);gradient.addColorStop(0,"#fff");gradient.addColorStop(.16,c.light);gradient.addColorStop(.52,c.main);gradient.addColorStop(1,c.dark);ctx.fillStyle=gradient;ctx.beginPath();ctx.arc(0,0,RADIUS,0,2*Math.PI);ctx.fill();ctx.strokeStyle="rgba(255,255,255,.25)";ctx.lineWidth=1.4;ctx.stroke();ctx.fillStyle="rgba(255,255,255,.38)";ctx.beginPath();ctx.arc(-7,-8,4,0,2*Math.PI);ctx.fill();drawPattern(c.pattern,c);ctx.restore()}
function drawPattern(pattern,c){ctx.save();ctx.globalAlpha=.2;ctx.strokeStyle=c.light;ctx.lineWidth=1;if(pattern==="lotus"){for(let i=0;i<5;i++){const a=-.8*Math.PI+i*.4*Math.PI;ctx.beginPath();ctx.moveTo(0,7);ctx.quadraticCurveTo(Math.cos(a)*10,Math.sin(a)*8,Math.cos(a)*14,Math.sin(a)*3);ctx.stroke()}}else if(pattern==="sun"){ctx.beginPath();ctx.arc(0,2,7,0,2*Math.PI);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4;ctx.beginPath();ctx.moveTo(Math.cos(a)*10,Math.sin(a)*10+2);ctx.lineTo(Math.cos(a)*15,Math.sin(a)*15+2);ctx.stroke()}}else if(pattern==="leaf"){ctx.beginPath();ctx.ellipse(0,2,5,10,-.7,0,2*Math.PI);ctx.stroke();ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(0,10);ctx.stroke()}else if(pattern==="wave"){ctx.beginPath();for(let i=-12;i<=12;i+=6)ctx.lineTo(i,Math.sin(i*.35)*5);ctx.stroke()}else if(pattern==="peacock"){ctx.beginPath();ctx.arc(0,4,10,Math.PI,2*Math.PI);ctx.stroke();ctx.beginPath();ctx.arc(0,4,4,Math.PI,2*Math.PI);ctx.stroke()}else{ctx.beginPath();ctx.arc(0,2,8,0,2*Math.PI);ctx.stroke()}ctx.restore()}

function drawSpecial(x,y,type,scale=1,alpha=1){const fills={laser:["#fff","#9ee7ff","#368fd4","#173d72"],bomb:["#ffb8a8","#d94b43","#260d17"],rainbow:["#ff687b","#ffcf63","#75df9b","#69b9ff","#b277e0"],sun:["#fffde2","#ffe98a","#e3a928","#9b5710"]};const arr=fills[type]||fills.laser;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x,y);ctx.scale(scale,scale);const g=ctx.createRadialGradient(-7,-8,2,0,0,RADIUS);g.addColorStop(0,arr[0]);g.addColorStop(.28,arr[1]);g.addColorStop(1,arr[arr.length-1]);ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,RADIUS,0,2*Math.PI);ctx.fill();ctx.strokeStyle="rgba(255,255,255,.34)";ctx.lineWidth=1.5;ctx.stroke();ctx.font="22px sans-serif";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(SPECIAL_ICONS[type]||"★",0,1);ctx.restore()}

function drawFallingBubbles(){for(const b of fallingBubbles){const sc=b.bounceScale;if(b.special)drawSpecial(b.x,b.y,b.special,sc,Math.max(.25,1-b.life*.15),b.rotation);else drawBubble(b.x,b.y,b.color,sc,Math.max(.25,1-b.life*.15),b.rotation);if(!b.grounded&&Math.abs(b.vy)>180){ctx.save();ctx.globalAlpha=.10;ctx.strokeStyle=COLORS[b.color]?.light||"#fff";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x,b.y-34);ctx.lineTo(b.x,b.y-8);ctx.stroke();ctx.restore()}}}

function drawMovingBubble(){if(!movingBubble)return;const b=movingBubble;ctx.save();for(let i=0;i<b.trail.length;i++){const t=b.trail[i];ctx.globalAlpha=(i/b.trail.length)*.14;ctx.fillStyle=b.special?"#fff":COLORS[b.color].light;ctx.beginPath();ctx.arc(t.x,t.y,4+i/b.trail.length*4,0,2*Math.PI);ctx.fill()}ctx.restore();b.special?drawSpecial(b.x,b.y,b.special,b.scale,1,b.rotation):drawBubble(b.x,b.y,b.color,b.scale,1,b.rotation,1+.04*b.squash,1-.03*b.squash)}

function drawAimGuide(){if(busy||paused||gameEnded||levelWon)return;let x=SHOOTER_X,y=SHOOTER_Y-12,dx=aimX-SHOOTER_X,dy=aimY-SHOOTER_Y;if(dy>-55)dy=-55;const len=Math.hypot(dx,dy)||1;dx/=len;dy/=len;const segments=[];let remaining=700,step=6,hit=!1;while(remaining>0&&!hit){const nx=x+dx*step,ny=y+dy*step;if(nx<=RADIUS||nx>=W-RADIUS){segments.push({x1:x,y1:y,x2:Math.max(RADIUS,Math.min(W-RADIUS,nx)),y2:ny});x=Math.max(RADIUS,Math.min(W-RADIUS,nx));dx*=-1}else if(ny<=TOP_Y+RADIUS){segments.push({x1:x,y1:y,x2:nx,y2:TOP_Y+RADIUS});hit=!0}else{let collision=!1;for(let r=0;r<grid.length&&!collision;r++)for(let q=0;q<COLS;q++){if(!grid[r][q])continue;const p=position(q,r);if(Math.hypot(p.x-nx,p.y-ny)<=RADIUS*1.65){segments.push({x1:x,y1:y,x2:p.x,y2:p.y});hit=!0;collision=!0;break}}if(!collision){x=nx;y=ny}}remaining-=step}ctx.save();ctx.setLineDash([7,8]);ctx.lineWidth=2;ctx.strokeStyle="rgba(255,248,220,.55)";for(const s of segments){ctx.beginPath();ctx.moveTo(s.x1,s.y1);ctx.lineTo(s.x2,s.y2);ctx.stroke()}ctx.setLineDash([]);if(segments.length){const last=segments[segments.length-1];ctx.fillStyle="rgba(255,248,220,.9)";ctx.beginPath();ctx.arc(last.x2,last.y2,4,0,2*Math.PI);ctx.fill()}ctx.restore()}

function drawLauncher(){const recoil=launcherRecoil*4,bounce=launcherBounce*3;ctx.save();ctx.translate(SHOOTER_X,SHOOTER_Y+recoil+bounce);ctx.fillStyle="rgba(5,15,35,.55)";ctx.beginPath();ctx.arc(0,0,30,0,2*Math.PI);ctx.fill();ctx.strokeStyle="rgba(255,235,180,.45)";ctx.lineWidth=2;ctx.stroke();ctx.save();ctx.rotate(Math.atan2(aimY-SHOOTER_Y,aimX-SHOOTER_X)+Math.PI/2);ctx.fillStyle="#d8bd6f";ctx.beginPath();ctx.roundRect(-9,-30,18,35,7);ctx.fill();ctx.restore();drawBubble(0,0,currentColor,.78,1);ctx.restore()}
function drawPopEffects(){for(const p of popEffects){const t=Math.min(1,Math.max(0,(p.life-p.delay)/p.max)),s=1+.8*t,a=1-t;p.special?drawSpecial(p.x,p.y,p.special,s,a):drawBubble(p.x,p.y,p.color,s,a)}}
function drawRings(){for(const r of rings){const t=r.life/r.max;ctx.save();ctx.globalAlpha=1-t;ctx.strokeStyle=COLORS[r.color].light;ctx.lineWidth=2;ctx.beginPath();ctx.arc(r.x,r.y,RADIUS+18*t,0,2*Math.PI);ctx.stroke();ctx.restore()}}
function drawImpacts(){for(const i of impacts){const t=i.life/i.max;ctx.save();ctx.globalAlpha=1-t;ctx.strokeStyle="rgba(255,248,220,.85)";ctx.lineWidth=2;ctx.beginPath();ctx.arc(i.x,i.y,10+16*t,0,2*Math.PI);ctx.stroke();ctx.restore()}}
function drawParticles(){for(const p of particles){const a=1-p.life/p.max;ctx.save();ctx.globalAlpha=Math.max(0,a);ctx.fillStyle=COLORS[p.color]?.light||"#fff";ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,2*Math.PI);ctx.fill();ctx.restore()}}
function drawSpecialBursts(){for(const b of specialBursts){const t=b.life/b.max,a=1-t;ctx.save();ctx.globalAlpha=a;if(b.type==="laser"){ctx.strokeStyle="rgba(180,238,255,.9)";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(b.x,30);ctx.lineTo(b.x,H-50);ctx.moveTo(20,b.y);ctx.lineTo(W-20,b.y);ctx.stroke()}else{ctx.strokeStyle=b.type==="bomb"?"rgba(255,170,120,.9)":"rgba(255,239,160,.8)";ctx.lineWidth=4;ctx.beginPath();ctx.arc(b.x,b.y,20+120*t,0,2*Math.PI);ctx.stroke()}ctx.restore()}}

function updateUI(){levelNumber.textContent=save.currentLevel;scoreText.textContent=score;bestText.textContent=Math.max(save.best,score);setPreviewColor(currentBubble,currentColor,currentSpecial);setPreviewColor(nextBubble,nextColor,nextSpecial);if(pressureDots){const dots=pressureDots.querySelectorAll("i");dots.forEach((dot,index)=>{if(index<missedShots){dot.style.background="#d8b56a";dot.style.boxShadow="0 0 8px rgba(216,181,106,.5)"}else{dot.style.background="rgba(166,194,224,.32)";dot.style.boxShadow="inset 0 1px rgba(255,255,255,.2)"}})}if(soundBtn)soundBtn.textContent=save.sound?"🔊":"🔇"}
function setPreviewColor(element,index,special){if(!element)return;if(special){element.style.background=special==="laser"?"radial-gradient(circle at 30% 25%,#fff,#9ee7ff 18%,#368fd4 55%,#173d72)":special==="bomb"?"radial-gradient(circle at 30% 25%,#ffb8a8,#d94b43 45%,#260d17)":special==="rainbow"?"linear-gradient(135deg,#ff687b,#ffcf63,#75df9b,#69b9ff,#b277e0)":"radial-gradient(circle at 30% 25%,#fffde2,#ffe98a 25%,#e3a928 65%,#9b5710)";element.textContent=SPECIAL_ICONS[special]||""}else{element.textContent="";const c=COLORS[index]||COLORS[0];element.style.background=`radial-gradient(circle at 30% 25%,#ffffff 0%,${c.light} 17%,${c.main} 52%,${c.dark} 100%)`}element.style.boxShadow="inset 5px 4px 7px rgba(255,255,255,.6),inset -6px -7px 9px rgba(0,0,0,.24),0 6px 12px rgba(0,0,0,.23)"}

function renderLevels(){levelsGrid.innerHTML="";for(let i=1;i<=MAX_LEVEL;i++){const btn=document.createElement("button");btn.className="level-btn";btn.textContent=i;if(i>save.unlocked){btn.disabled=!0;btn.textContent="🔒 "+i}else{if(save.completed.includes(i))btn.classList.add("completed");if(i===save.currentLevel)btn.classList.add("current");btn.onclick=()=>{save.currentLevel=i;saveGame();showScreen(gameScreen);createLevel()}}levelsGrid.appendChild(btn)}}
function showScreen(screen){homeScreen.classList.add("hidden");levelsScreen.classList.add("hidden");gameScreen.classList.add("hidden");screen.classList.remove("hidden")}

function showResult(success){resultPanel.classList.remove("hidden");resultIcon.textContent=success?"🪷":"⬇️";resultTitle.textContent=success?"बहुत बढ़िया!":"छत बहुत नीचे आ गई";resultText.textContent=success?(save.currentLevel>=MAX_LEVEL?"गजब! आपने सभी 50 स्तर पूरे कर लिए।":"बुलबुले मिलाकर स्तर पूरा कर दिया!"):"कोई बात नहीं। फिर से कोशिश करते हैं।";resultScore.textContent=score;resultPrimaryBtn.textContent=success?(save.currentLevel<MAX_LEVEL?"अगला स्तर":"स्तर चुनें"):"फिर से खेलें";resultPrimaryBtn.onclick=()=>{resultPanel.classList.add("hidden");if(success&&save.currentLevel<MAX_LEVEL){save.currentLevel++;saveGame();createLevel()}else if(success){renderLevels();showScreen(levelsScreen)}else createLevel()};resultSecondaryBtn.onclick=()=>{resultPanel.classList.add("hidden");renderLevels();showScreen(levelsScreen)}}

settingsBtn.onclick=()=>settingsPanel.classList.remove("hidden");closeSettingsBtn.onclick=()=>settingsPanel.classList.add("hidden");resetProgressBtn.onclick=()=>{if(!window.confirm("क्या आप पूरी खेल प्रगति रीसेट करना चाहते हैं?"))return;save={...defaultSave,completed:[],bestScores:{}};saveGame();settingsPanel.classList.add("hidden");renderLevels();showScreen(levelsScreen)};
function initAudio(){if(!save.sound)return;try{audioContext||(audioContext=new(window.AudioContext||window.webkitAudioContext)());audioContext.state==="suspended"&&audioContext.resume()}catch{}}
function playSound(frequency,duration,type="sine",volume=.03){if(!save.sound)return;try{initAudio();if(!audioContext)return;const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,audioContext.currentTime);gain.gain.setValueAtTime(volume,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+duration);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+duration)}catch{}}
soundBtn.onclick=()=>{save.sound=!save.sound;saveGame();updateUI()};

function updateAim(clientX,clientY){const rect=canvas.getBoundingClientRect();if(!rect.width||!rect.height)return;aimX=(clientX-rect.left)*W/rect.width;aimY=(clientY-rect.top)*H/rect.height;aimX=Math.max(5,Math.min(W-5,aimX));aimY=Math.max(80,Math.min(SHOOTER_Y-25,aimY))}
function releasePointer(event){if(!pointerHolding)return;if(activePointerId!==null&&event.pointerId!==activePointerId)return;event.preventDefault();updateAim(event.clientX,event.clientY);pointerHolding=!1;const id=activePointerId;activePointerId=null;try{if(id!==null&&canvas.hasPointerCapture(id))canvas.releasePointerCapture(id)}catch{}shoot()}
canvas.addEventListener("pointerdown",event=>{if(gameScreen.classList.contains("hidden")||paused||busy||gameEnded||levelWon||ceilingAnimation)return;event.preventDefault();pointerHolding=!0;activePointerId=event.pointerId;updateAim(event.clientX,event.clientY);try{canvas.setPointerCapture(event.pointerId)}catch{}});
canvas.addEventListener("pointermove",event=>{if(paused||gameEnded||levelWon)return;if(pointerHolding&&activePointerId!==null&&event.pointerId!==activePointerId)return;updateAim(event.clientX,event.clientY)});
canvas.addEventListener("pointerup",releasePointer);canvas.addEventListener("pointercancel",event=>{if(activePointerId===event.pointerId){pointerHolding=!1;activePointerId=null}});
window.addEventListener("blur",()=>{pointerHolding=!1;activePointerId=null});

startBtn.onclick=()=>{renderLevels();showScreen(levelsScreen)};homeLevelsBtn.onclick=()=>{renderLevels();showScreen(levelsScreen)};backHomeBtn.onclick=()=>showScreen(homeScreen);gameBackBtn.onclick=()=>{renderLevels();showScreen(levelsScreen)};

document.addEventListener("visibilitychange",()=>{if(document.hidden){paused=!0;pointerHolding=!1;activePointerId=null;lastTime=performance.now()}else{paused=!1;lastTime=performance.now();updateAimFromCenterIfNeeded()}});window.addEventListener("pageshow",()=>{paused=!1;lastTime=performance.now()});window.addEventListener("pagehide",()=>{paused=!0;pointerHolding=!1;activePointerId=null});window.addEventListener("resize",()=>{lastTime=performance.now();updateAimFromCenterIfNeeded()});
function updateAimFromCenterIfNeeded(){aimX=Math.max(5,Math.min(W-5,aimX));aimY=Math.max(80,Math.min(SHOOTER_Y-25,aimY))}

function loop(timestamp){const dt=Math.min(.033,(timestamp-lastTime)/1000||0);lastTime=timestamp;if(!gameScreen.classList.contains("hidden")){update(dt);draw()}requestAnimationFrame(loop)}
updateUI();renderLevels();showScreen(homeScreen);requestAnimationFrame(loop)})();
